config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'posts#index'

  resources :users, only: %i[show edit update]

  resources :posts do
    resources :comments, only: %i[new create destroy]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: { public: 0, private: 1, archived: 2 }, _suffix: :status

  validates :title, :body, presence: true

  belongs_to :user
  has_many_attached :images
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_validation :set_name, on: :create

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  private

  def set_name
    self.name = "Name №#{rand(777)}" if name.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # when a user edits a profile
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :current_user_can_edit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :account_update,
      keys: [:password, :password_confirmation, :current_password]
    )
  end

  def current_user_can_edit?(model)
    user_signed_in? && (
      model.user == current_user || (model.try(:post).present? && model.post.user == current_user)
    )
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: %i[create destroy]
  before_action :set_comment, only: [:destroy]

  def new
    @post = current_user.posts.build
  end

  def create
    @new_comment = @post.comments.build(comment_params)
    @new_comment.user = current_user
    @new_comment.save
    redirect_to post_path(@post)
  end

  def destroy
    message = { notice: I18n.t('controllers.comments.destroyed') }

    if current_user_can_edit?(@comment)
      @comment.destroy!
    else
      message = { alert: I18n.t('controllers.comments.error') }
    end

    redirect_to post_path(@post), message
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:user_name, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end

  def show
    @comments = @post.comments if @post.comments.any?
    @new_comment = @post.comments.build(params[:comment])
  end

  def new = @post = Post.new

  def edit; end

  def create
    @post = current_user.posts.create(post_params)
    redirect_to user_path(current_user)
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy

    redirect_to user_path(current_user), status: :see_other
  end

  private

  def set_post = @post = Post.find(params[:id])

  def post_params
    params.require(:post).permit(:title, :body, images: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_user, only: [:show]
  before_action { I18n.locale = :ru }

  def index = @users = User.all.count

  def show = @comments = @user.comments

  def edit; end

  def update
    if current_user.update(user_params)
      redirect_to current_user, notice: 'User was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user = @user = User.find(params[:id])

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="buffer-bottom py-4">
  <div class="container text-center">
    <div class="row">
      <div class="col-4" >
        <div style="background-color: #CCCCCC">Пользователь: <%= comment.user_name %></div>
      </div>
      <div class="col p-3" style="background-color: #EFEFEF">
        <%= comment.body %>
      </div>

      <% if current_user_can_edit?(comment) && comment.id.present? %>
        <em class=""><%= comment.created_at.strftime("%d %b. %Y %H:%M") %></em>
        <%= button_to(t('links.delete'), post_comment_path(comment.post, comment),
                      method: :delete, data: { confirm: t('.destroy_confirm') }, class: 'btn btn-outline-danger btn-sm'
            ) %>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="row">
  <div class="col-md-6 my-4">
    <%= form_for [@post, comment] do |f| %>
      <%= render partial: 'partials/form_errors', locals: {model: comment} %>

      <% unless current_user.present? && @post.user_id == current_user.id %>
        <div class="form-group">
          <%= f.label :user_name %>
          <%= f.text_field :user_name, class: 'form-control' %>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :comment %>
        <%= f.text_area :body, class: 'form-control mt-3', placeholder: 'Your text' %>
      </div>

      <div class="actions mt-4">
        <input class="btn btn-success btn-block" type="submit" value="<%= t 'form.save' %>">
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid justify-content-start">
    <a class="navbar-brand" href="#">
      <%= link_to t('app.name'), root_path, class: 'navbar-brand' %>
    </a>
  </div>
</nav>

<div class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid justify-content-end">
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li><%= link_to t('new_post'), new_post_path(current_user), class: 'nav-link' %></li>
        <li><%= link_to "#{current_user.name}", current_user, class: 'nav-link' %></li>
        <li><%= link_to t('links.edit_profile'), edit_user_path(current_user), class: 'nav-link' %></li>
        <li><%= button_to t('links.log_off'), destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
      <% else %>
        <li><%= link_to t('links.sign_in'), new_user_session_path, class: 'nav-link' %></li>
        <li><%= link_to t('links.register'), new_user_registration_path, class: 'nav-link' %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="content">
  <div class="container">
    <% if flash.any? %>
      <div class="content-wrapper buffer-both">
        <% flash.each do |name, message| %>
          <%= content_tag :div, message, class: "flash-#{name}" %>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

app/views/partials/_form_errors.html.erb
<%# Form of errors, if any %>
<% errors = model.errors %>

<% if errors.any? %>
  <div class="alert alert-danger">
    <div class="lead buffer-bottom">
      <%= t('.info', count: errors.count) %>
    </div>

    <ul>
      <% errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%# Post edit form %>
<div class="row">
  <div class="col-md-6 my-4">
    <%= form_for post , html: { multipart: true } do |f| %>
      <%= render partial: 'partials/form_errors', locals: { model: current_user } %>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_field :body, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :images, multiple: true, class: 'form-control' %>
      </div>
      <div class="actions mt-4">
        <input class="btn btn-success btn-block" type="submit" value="<%= t 'form.save' %>">
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="buffer-bottom py-4">
  <%= link_to post.title, post %>
</div>

app/views/posts/_user_post.html.erb
<div class="buffer-bottom py-4">
  <% user.posts.each do |post| %>
    <p>
      <strong>Title:</strong>
      <%= link_to post.title, post %>
    </p>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

<p class="buffer-top">
  <%= button_to t('links.delete'), @post, method: :delete, class: 'btn btn-outline-danger' %>
</p>

<div class="py-4">
  <%= link_to t('links.to_return'), :back, class: 'btn btn-secondary' %>
</div>

app/views/posts/index.html.erb
<h2>Posts</h2>

<%= render @posts %>

<div class="apple_pagination">
  <%= will_paginate @posts, :container => false %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

<div class="py-4">
  <%= link_to t('links.to_return'), :back, class: 'btn btn-secondary' %>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<% if @post.images.attached? %>
  <% @post.images.each do |image| %>
    <% if image.image? %>
      <div class="d-inline-block">
        <%=link_to image_tag(image.variant(resize_to_limit: [100, 100])), image %><br />
      </div>
    <% else %>
      <%= link_to image.filename, rails_blob_path(image, disposition: "attachment") %>
    <% end %>
  <% end %>
<% end %>

<p class="buffer-top"><%= @post.body %></p>

<%= render partial: 'comments/comment', collection: @comments %>

<% if user_signed_in? && @post.user_id == current_user.id %>
  <%= render partial: 'comments/form', locals: {comment: @new_comment || @post.comments.build} %>

  <%= link_to t('links.edit'), edit_post_path(@post) , class: 'btn btn-outline-warning'%>

  <div class="py-4">
    <%= link_to t('links.to_return'), user_path(current_user), class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%# User edit form %>
<div class="row">
  <div class="col-md-4 my-4">
    <%= form_for user, html: { multipart: true } do |f| %>
      <%= render partial: 'partials/form_errors', locals: { model: user } %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="actions mt-4">
        <input class="btn btn-success btn-block" type="submit" value="<%= t 'form.save' %>">
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h2 class="border-bottom text-dark"><%= t('heading.еdit_profile') %></h2>
<div class="col-md-6 buffer-top py-4">
  <%= render 'form', user: current_user %><br>

  <p class="buffer-top">
    <%= link_to t('links.сhange_password'), edit_user_registration_path, class: 'btn btn-outline-warning' %>
  </p>

  <div class="py-4">
    <%= link_to t('links.to_return'), :back, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/users/index.html.erb
<p>Users count: <%= @users %></p>

app/views/users/show.html.erb
<% if current_user %>
  <div class="text-center mt-5">
    <table class="table table-light">
      <thead>
      <tr>
        <th class="display-6"><%= t '.name' %></th>
        <th class="display-6"><%= t '.email'%></th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= current_user.name %></td>
        <td><%= current_user.email %></td>
      </tr>
      </tbody>
    </table><br>

    <div class="container text-center">
      <div class="row">
        <div class="col">
          <h2 class="mt-5">My posts</h2>
          <%= render partial: 'posts/user_post', locals: { user: current_user } %>
        </div>
        <div class="col">
          <h2 class="mt-5">My comments</h2>
          <%= render partial: 'comments/comment', collection: @comments %>
        </div>
      </div>
    </div>

  </div>
<% else %>
  <р2>Not your page!</р2>
<% end %>